embed_images: off
javascript_compressor: yui

javascripts:
  csvva:
    - public/javascripts/prototype.js
    - public/javascripts/effects.js
    - public/javascripts/dragdrop.js
    - public/javascripts/controls.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
#    - public/javascripts/**/*.js


  asgard:
    - public/*/javascripts/**/*.js
    - public/*/core_javascripts/**/*.js

stylesheets:
  csvva:
    - public/stylesheets/**/*.css

  asgard:
    - public/ext/resources/css/ext-all-notheme.css
    - public/ext/resources/css/xtheme-gray.css
    - public/*/stylesheets/**/*.css
