embed_images: off
javascript_compressor: yui

javascripts:
  cid:
    - public/javascripts/jquery-1.6.js
    - public/javascripts/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.spinner.js
    - public/javascripts/rails.js
    - public/javascripts/flarc/**/*.js

  csvva:
    - public/javascripts/jquery-1.6.js
    - public/javascripts/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.spinner.js
    - public/javascripts/rails.js
    - public/javascripts/flarc/**/*.js


  asgard:
    - public/*/javascripts/**/*.js
    - public/*/core_javascripts/**/*.js

stylesheets:
  cid:
    - public/stylesheets/*.css
    - public/stylesheets/cid/**/*.css
    - public/stylesheets/custom-theme/jquery-ui-1.8.11.custom.css
#    - public/stylesheets/ui-lightness/jquery-ui-1.8.11.custom.css

  csvva:
    - public/stylesheets/*.css
    - public/stylesheets/csvva/**/*.css
    - public/stylesheets/custom-theme/jquery-ui-1.8.11.custom.css
#    - public/stylesheets/ui-lightness/jquery-ui-1.8.11.custom.css

  asgard:
    - public/ext/resources/css/ext-all-notheme.css
    - public/ext/resources/css/xtheme-gray.css
    - public/*/stylesheets/**/*.css
