embed_images: off
javascript_compressor: yui

javascripts:
  cid:
#    - public/javascripts/prototype.js
#    - public/javascripts/effects.js
#    - public/javascripts/dragdrop.js
#    - public/javascripts/controls.js
    - public/javascripts/jquery-1.5.1.min.js
    - public/javascripts/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

  csvva:
#    - public/javascripts/prototype.js
#    - public/javascripts/effects.js
#    - public/javascripts/dragdrop.js
#    - public/javascripts/controls.js
    - public/javascripts/jquery-1.5.1.min.js
    - public/javascripts/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
#    - public/javascripts/**/*.js


  asgard:
    - public/*/javascripts/**/*.js
    - public/*/core_javascripts/**/*.js

stylesheets:
  cid:
    - public/stylesheets/common.css
    - public/stylesheets/cid/**/*.css
    - public/stylesheets/ui-lightness/jquery-ui-1.8.11.custom.css

  csvva:
    - public/stylesheets/common.css
    - public/stylesheets/csvva/**/*.css
    - public/stylesheets/ui-lightness/jquery-ui-1.8.11.custom.css

  sap:
    - public/stylesheets/common.css
    - public/stylesheets/sap/**/*.css
    - public/stylesheets/ui-lightness/jquery-ui-1.8.11.custom.css

  asgard:
    - public/ext/resources/css/ext-all-notheme.css
    - public/ext/resources/css/xtheme-gray.css
    - public/*/stylesheets/**/*.css
