embed_images: on
javascript_compressor: yui
gzip_assets: on

javascripts:
  default:
    - public/javascripts/prototype.js
    - public/javascripts/effects.js
    - public/javascripts/application.js
    - public/javascripts/controls.js
    - public/javascripts/dragdrop.js
    - public/javascripts/lightbox.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  csvva:
    - public/stylesheets/csvva.css
    - public/stylesheets/lightbox.css
